"""QLoRA fine-tuning of the base model on Spider instruction data.

Pipeline position: after src/preprocessing.py, before src/merge_and_quantize.py
and src/baseline_prompting.py (for fine-tuned predictions). Consumes
data/processed/train.jsonl; saves LoRA adapter checkpoints only (the base
model is never modified in place).

Stack: transformers + peft + bitsandbytes + trl (SFTTrainer).

Everything is configurable via YAML (configs/default.yaml) with CLI overrides:
model, LoRA r/alpha/dropout/target_modules, epochs, batch size, gradient
accumulation, learning rate, scheduler, seq length, response template, etc.
For ablations, copy the YAML and change values — do not edit this file.

Single-T4 (free Colab, 16 GB) feasibility, defaults chosen for it:
    - base model loaded in 4-bit NF4 (double quant) compute dtype fp16
    - gradient checkpointing (non-reentrant)
    - per_device_train_batch_size=4 x gradient_accumulation_steps=4
    - paged_adamw_8bit optimizer
    - max_seq_length=1024 (Spider schemas are long but rarely longer)
    Roughly ~5-6 GB peak for a 3B model + adapter — comfortable on a T4.

Logging: train loss every `logging_steps` steps and eval loss every
`eval_steps` (on a small held-out slice of TRAIN — dev.jsonl is the benchmark
and is never trained or model-selected on). The full log history is dumped to
<output_dir>/log_history.json, and the resolved config (defaults <- YAML <-
CLI) to <output_dir>/resolved_config.yaml for reproducibility.

Example (Colab, after uploading this repo and mounting data):
    python src/train_qlora.py --config configs/default.yaml
    python src/train_qlora.py --config configs/lora_r8.yaml --output-dir outputs/r8
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

import torch  # noqa: E402
import yaml  # noqa: E402
from transformers import (  # noqa: E402
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
)
from peft import LoraConfig, prepare_model_for_kbit_training  # noqa: E402
from trl import SFTConfig, SFTTrainer  # noqa: E402

from src.config_utils import deep_update, get, load_yaml  # noqa: E402
from src.preprocessing import SYSTEM_PROMPT, read_jsonl  # noqa: E402


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", default=None, help="YAML config (on top of configs/default.yaml)")
    # Common ablation knobs; anything else goes through the YAML file.
    parser.add_argument("--model", default=None)
    parser.add_argument("--train-file", default=None)
    parser.add_argument("--output-dir", default=None)
    parser.add_argument("--epochs", type=float, default=None)
    parser.add_argument("--learning-rate", type=float, default=None)
    parser.add_argument("--batch-size", type=int, default=None,
                        help="per-device train batch size")
    parser.add_argument("--grad-accum", type=int, default=None)
    parser.add_argument("--lora-r", type=int, default=None)
    parser.add_argument("--lora-alpha", type=int, default=None)
    parser.add_argument("--max-seq-length", type=int, default=None)
    parser.add_argument("--response-template", default=None,
                        help="e.g. '<|im_start|>assistant\\n' for Qwen -> completion-only loss")
    parser.add_argument("--val-fraction", type=float, default=None)
    parser.add_argument("--seed", type=int, default=None)
    parser.add_argument("--max-steps", type=int, default=None,
                        help="Smoke-test override: cap total optimizer steps")
    return parser.parse_args()


def resolve_config(args: argparse.Namespace) -> dict:
    """configs/default.yaml < --config YAML < CLI flags (None = not given)."""
    cfg: dict = {}
    default_cfg_path = ROOT / "configs" / "default.yaml"
    if default_cfg_path.exists():
        cfg = load_yaml(default_cfg_path)
    if args.config:
        cfg = deep_update(cfg, load_yaml(args.config))
    return deep_update(
        cfg,
        {
            "model": {"base_model": args.model},
            "data": {
                "train_file": args.train_file,
                "max_seq_length": args.max_seq_length,
                "val_fraction": args.val_fraction,
                "seed": args.seed,
            },
            "lora": {"r": args.lora_r, "lora_alpha": args.lora_alpha},
            "training": {
                "output_dir": args.output_dir,
                "num_train_epochs": args.epochs,
                "learning_rate": args.learning_rate,
                "per_device_train_batch_size": args.batch_size,
                "gradient_accumulation_steps": args.grad_accum,
                "response_template": args.response_template,
                "max_steps": args.max_steps,
                "seed": args.seed,
            },
        },
    )


def load_and_split_train(cfg: dict) -> tuple[list[dict], list[dict]]:
    """Read processed train.jsonl and carve a small val slice (loss logging only).

    dev.jsonl is NEVER used here — it is the benchmark. The split is seeded and
    the val indices are written next to the output for reproducibility.
    """
    train_file = get(cfg, "data.train_file", "data/processed/train.jsonl")
    val_fraction = float(get(cfg, "data.val_fraction", 0.02))
    seed = get(cfg, "data.seed", 42)

    records = read_jsonl(train_file)
    rng = random.Random(seed)
    idx = list(range(len(records)))
    rng.shuffle(idx)
    n_val = max(1, int(len(records) * val_fraction)) if val_fraction > 0 else 0
    val_idx = set(idx[:n_val])
    train = [r for i, r in enumerate(records) if i not in val_idx]
    val = [r for i, r in enumerate(records) if i in val_idx]
    print(f"Loaded {len(records)} examples from {train_file} "
          f"-> {len(train)} train / {len(val)} val (seed={seed})")
    return train, val


def format_records(records: list[dict], tokenizer) -> list[dict]:
    """Apply the model's chat template to each record -> datasets with a 'text' field.

    Pre-formatting (rather than a TRL formatting_func) keeps the code working
    across trl versions: SFTTrainer just consumes dataset_text_field="text".
    """
    texts = []
    for rec in records:
        messages = [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": rec["instruction"]},
            {"role": "assistant", "content": rec["output"]},
        ]
        text = tokenizer.apply_chat_template(messages, tokenize=False)
        # Templates that don't end with the EOS token need it appended, or the
        # model never learns to stop after the SQL.
        eos = tokenizer.eos_token or ""
        if eos and not text.rstrip().endswith(eos):
            text = text.rstrip() + eos
        texts.append({"text": text})
    return texts


def build_sft_config(cfg: dict) -> SFTConfig:
    """Map the YAML training/data sections onto SFTConfig (TrainingArguments)."""
    out_dir = get(cfg, "training.output_dir", "outputs/qlora_run")
    fp16 = bool(get(cfg, "training.fp16", True))
    kwargs = dict(
        output_dir=out_dir,
        num_train_epochs=float(get(cfg, "training.num_train_epochs", 3)),
        per_device_train_batch_size=int(get(cfg, "training.per_device_train_batch_size", 4)),
        per_device_eval_batch_size=int(get(cfg, "training.per_device_eval_batch_size", 4)),
        gradient_accumulation_steps=int(get(cfg, "training.gradient_accumulation_steps", 4)),
        learning_rate=float(get(cfg, "training.learning_rate", 2e-4)),
        lr_scheduler_type=get(cfg, "training.lr_scheduler_type", "cosine"),
        warmup_ratio=float(get(cfg, "training.warmup_ratio", 0.03)),
        weight_decay=float(get(cfg, "training.weight_decay", 0.0)),
        logging_steps=int(get(cfg, "training.logging_steps", 10)),
        eval_strategy=get(cfg, "training.eval_strategy", "steps"),
        eval_steps=int(get(cfg, "training.eval_steps", 100)),
        save_strategy=get(cfg, "training.save_strategy", "epoch"),
        save_total_limit=int(get(cfg, "training.save_total_limit", 2)),
        fp16=fp16,
        bf16=not fp16 and bool(get(cfg, "training.bf16", False)),
        optim=get(cfg, "training.optim", "paged_adamw_8bit"),
        gradient_checkpointing=bool(get(cfg, "training.gradient_checkpointing", True)),
        gradient_checkpointing_kwargs={"use_reentrant": False},
        report_to=get(cfg, "training.report_to", "none"),
        seed=int(get(cfg, "training.seed", 42)),
        # SFT-specific:
        dataset_text_field="text",
        max_seq_length=int(get(cfg, "data.max_seq_length", 1024)),
        packing=False,
    )
    max_steps = get(cfg, "training.max_steps")
    if max_steps:
        kwargs["max_steps"] = int(max_steps)
    return SFTConfig(**kwargs)


def main() -> None:
    args = parse_args()
    cfg = resolve_config(args)

    model_name = get(cfg, "model.base_model", "Qwen/Qwen2.5-Coder-3B-Instruct")
    out_dir = Path(get(cfg, "training.output_dir", "outputs/qlora_run"))
    out_dir.mkdir(parents=True, exist_ok=True)

    # Persist the fully resolved configuration for this run (ablation trail).
    with open(out_dir / "resolved_config.yaml", "w", encoding="utf-8") as f:
        yaml.safe_dump(cfg, f, sort_keys=False)

    if not torch.cuda.is_available():
        print("WARNING: no CUDA device detected. QLoRA training expects a GPU "
              "(free-tier Colab T4). Continuing, but it will not finish.")
    fp16 = bool(get(cfg, "training.fp16", True))

    tokenizer = AutoTokenizer.from_pretrained(model_name, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
        bnb_4bit_compute_dtype=torch.float16 if fp16 else torch.bfloat16,
    )
    model = AutoModelForCausalLM.from_pretrained(
        model_name,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
    )
    model.config.use_cache = False  # incompatible with gradient checkpointing

    if bool(get(cfg, "training.gradient_checkpointing", True)):
        model = prepare_model_for_kbit_training(
            model, use_gradient_checkpointing=True
        )

    lora_config = LoraConfig(
        task_type="CAUSAL_LM",
        r=int(get(cfg, "lora.r", 16)),
        lora_alpha=int(get(cfg, "lora.lora_alpha", 32)),
        lora_dropout=float(get(cfg, "lora.lora_dropout", 0.05)),
        target_modules=get(cfg, "lora.target_modules",
                           ["q_proj", "k_proj", "v_proj", "o_proj",
                            "gate_proj", "up_proj", "down_proj"]),
        bias=get(cfg, "lora.bias", "none"),
    )

    train_records, val_records = load_and_split_train(cfg)
    from datasets import Dataset

    train_ds = Dataset.from_list(format_records(train_records, tokenizer))
    val_ds = Dataset.from_list(format_records(val_records, tokenizer)) if val_records else None

    sft_config = build_sft_config(cfg)

    data_collator = None
    response_template = get(cfg, "training.response_template")
    if response_template:
        from trl import DataCollatorForCompletionOnlyLM

        # Loss on the SQL completion only (not the schema prompt).
        data_collator = DataCollatorForCompletionOnlyLM(
            response_template=response_template, tokenizer=tokenizer
        )
        print(f"Completion-only loss enabled (response_template={response_template!r})")

    trainer = SFTTrainer(
        model=model,
        args=sft_config,
        train_dataset=train_ds,
        eval_dataset=val_ds,
        peft_config=lora_config,
        # `tokenizer=` (not the newer `processing_class=`) works across the
        # whole trl/transformers band pinned in requirements.txt.
        tokenizer=tokenizer,
        data_collator=data_collator,
    )

    if hasattr(trainer.model, "print_trainable_parameters"):
        trainer.model.print_trainable_parameters()

    print(f"\nTraining QLoRA on {model_name}")
    print(f"  LoRA r={lora_config.r} alpha={lora_config.lora_alpha} "
          f"dropout={lora_config.lora_dropout}")
    print(f"  effective batch = {sft_config.per_device_train_batch_size} x "
          f"{sft_config.gradient_accumulation_steps} (accum) = "
          f"{sft_config.per_device_train_batch_size * sft_config.gradient_accumulation_steps}")
    print(f"  output_dir = {out_dir}")

    trainer.train()

    final_dir = out_dir / "final_adapter"
    trainer.save_model(str(final_dir))
    tokenizer.save_pretrained(str(final_dir))
    with open(out_dir / "log_history.json", "w", encoding="utf-8") as f:
        json.dump(trainer.state.log_history, f, indent=2)

    print(f"\nSaved final adapter -> {final_dir}")
    print(f"Log history (train/eval loss per step) -> {out_dir / 'log_history.json'}")
    print("\nNext steps:")
    print(f"  predictions : python src/baseline_prompting.py "
          f"--adapter {final_dir} --out preds/qlora.jsonl")
    print(f"  merge + GGUF: python src/merge_and_quantize.py "
          f"--adapter {final_dir} --gguf")


if __name__ == "__main__":
    main()
